[package]
name = "demo-app"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
iced.workspace = true
iced-code-editor = { path = "../iced-code-editor", features = ["lsp-process", "two-face"] }
iced_aw = "0.13.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
opener = { version = "0.8.5", features = ["reveal"] }
rfd = "0.17"
url = "2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
rfd = "0.17"

[dev-dependencies]
iced_test = "0.14"

[[bin]]
name = "demo-editor"
path = "src/main.rs"

[lints]
workspace = true
